// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8FwFwzAKJIpk6Ns3NkpSICO8XyzbHwF4',
    appId: '1:532106864560:web:3a5031dba8505be2a01875',
    messagingSenderId: '532106864560',
    projectId: 'jamiah-timetable',
    authDomain: 'jamiah-timetable.firebaseapp.com',
    storageBucket: 'jamiah-timetable.firebasestorage.app',
    measurementId: 'G-ZC30MGHCQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjX1pBz6Gl9UXd9ItjIWrN1lcgp3ZVuMQ',
    appId: '1:532106864560:android:04ffd64f95ae0f44a01875',
    messagingSenderId: '532106864560',
    projectId: 'jamiah-timetable',
    storageBucket: 'jamiah-timetable.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH9HXZdhngAVtgOvM96zIu9BpVvgdw4wI',
    appId: '1:532106864560:ios:b258cd7f3f35d936a01875',
    messagingSenderId: '532106864560',
    projectId: 'jamiah-timetable',
    storageBucket: 'jamiah-timetable.firebasestorage.app',
    iosBundleId: 'com.diwizon.jamiahNamazTimetable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH9HXZdhngAVtgOvM96zIu9BpVvgdw4wI',
    appId: '1:532106864560:ios:b258cd7f3f35d936a01875',
    messagingSenderId: '532106864560',
    projectId: 'jamiah-timetable',
    storageBucket: 'jamiah-timetable.firebasestorage.app',
    iosBundleId: 'com.diwizon.jamiahNamazTimetable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8FwFwzAKJIpk6Ns3NkpSICO8XyzbHwF4',
    appId: '1:532106864560:web:d2bbcf3443ac8408a01875',
    messagingSenderId: '532106864560',
    projectId: 'jamiah-timetable',
    authDomain: 'jamiah-timetable.firebaseapp.com',
    storageBucket: 'jamiah-timetable.firebasestorage.app',
    measurementId: 'G-PWLG3XDXVP',
  );
}
